---
title: "makeImages.Rmd"
author: "Rex Sumsion"
date: "3/28/2018"
output: html_document
---


```{r}
setwd("~/Desktop/CAMDA_CMAP_Challenge")
#setwd("~/Desktop")
data <- read.table("numTrees.txt", sep="\t", header=TRUE)
data
```

```{r}
accuracyMean <- tapply(data$accuracy,data$parameterTested,mean)
sensitivityMean <- tapply(data$sensitivity,data$parameterTested,mean)
specificityMean <- tapply(data$specificity,data$parameterTested,mean)
mccMean <- tapply(data$mcc,data$parameterTested,mean)

accuracyMean <- data.frame(accuracyMean)
parameterTested <- row.names(accuracyMean)

prepared.data <- data.frame(parameterTested,accuracyMean,sensitivityMean,specificityMean,mccMean) 
prepared.data$parameterTested <- as.numeric(as.character(prepared.data$parameterTested))
prepared.data
```

```{r}
library(ggplot2)
library(gridExtra)

accuracyPlot <- ggplot(prepared.data,aes(parameterTested,accuracyMean))+
  geom_line() +
  theme_classic() +
  geom_vline(xintercept=25, linetype="dashed", color = "red") +
  labs(x = "Number of Trees", y = "Mean Accuracy", title="Accuracy")

specificityPlot <- ggplot(prepared.data,aes(parameterTested,specificityMean))+
  geom_line() +
  theme_classic() +
  geom_vline(xintercept=25, linetype="dashed", color = "red") +
  labs(x = "Number of Trees", y = "Mean Specificity", title="Specificity")

sensitivityPlot <- ggplot(prepared.data,aes(parameterTested,sensitivityMean))+
  geom_line() +
  theme_classic() +
  geom_vline(xintercept=25, linetype="dashed", color = "red") +
  labs(x = "Number of Trees", y = "Mean Sensitivity", title="Sensitivity")

mccPlot <- ggplot(prepared.data,aes(parameterTested,mccMean))+
  geom_line() +
  theme_classic() +
  geom_vline(xintercept=25, linetype="dashed", color = "red") +
  labs(x = "Number of Trees", y = "Mean MCC", title="MCC")

#accuracyPlot
#specificityPlot
#sensitivityPlot
#mccPlot

grid.arrange(accuracyPlot,specificityPlot,sensitivityPlot,mccPlot, nrow = 2)
getwd()
ggsave("optomization.png",grid.arrange(accuracyPlot,specificityPlot,sensitivityPlot,mccPlot, nrow = 2))
```

```{r}
## change location for your algorithm and parameter
setwd("ParameterOptomizationGraphs/randomForest/max_leaf_nodes")

## 
ggsave("accuracymax_leaf_nodes.png",accuracyPlot)
ggsave("specificitymax_leaf_nodes.png",accuracyPlot)
ggsave("sensitivitymax_leaf_nodes.png",accuracyPlot)
ggsave("mccmax_leaf_nodes.png",accuracyPlot)
```

